spring:
  application:
    name: login-sample
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306?employees?useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
