spring:
  application:
    name: login-sample
  datasource:
    url: jdbc:mysql://localhost:3306/employees?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true

